import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { AppProvider } from "./context/AppContext";
import Footer from "./components/Footer";
import { ThemeSwitcherProvider } from "./components/ThemeSwitcherProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "next-todo-list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ThemeSwitcherProvider>
            <AppProvider author="NextDeveloper" email="dev@nextjs.com">
              <div className="flex flex-col min-h-screen bg-[#f0f2f5] dark:bg-gray-950 text-foreground">
                <main className="grow flex flex-col">
                  {children}
                </main>
                <Footer />
              </div>
            </AppProvider>
          </ThemeSwitcherProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
